name: Build and Deploy Woori Node App

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted
  build-and-deploy:
    runs-on: self-hosted # Runner가 설치된 VM에서 실행
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: install pnpm and build
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: pnpm 설치중..
        run: npm install -g pnpm

      - name: 종속성 설치중...
        run: pnpm install

      - name: 빌드 중..
        run: pnpm build
