name: Build test for Woori Node App developers

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Proceed with Build
        run: echo "Runner is ready."

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean up old Docker containers and images
        run: |
          docker rm woori-node-app -f || true
          docker rmi woori-node-app || true

      - name: Build Docker Image
        run: |
          docker build -t woori-node-app .

      - name: Run Docker Container
        run: |
          docker run -d --name woori-node-app -p 80:80 woori-node-app
