name: Build test for Woori Node App developers

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Proceed with Build
        run: echo "Runner is ready."

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Clean up old Docker containers and images
        run: |
          docker ps -q --filter "name=woori-node-app" | xargs -r docker stop
          docker ps -aq --filter "name=woori-node-app" | xargs -r docker rm -f
          docker images -q woori-node-app | xargs -r docker rmi -f

      - name: Build Docker Image
        run: |
          docker build -t woori-node-app .

      - name: Run Docker Container
        run: |
          docker run -d --name woori-node-app -p 80:80 woori-node-app
