name: Build test server for Woori Node App developers

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Proceed with Build
        run: echo "Runner is ready."

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: 하드리셋(기존 이미지 및 컨테이너 삭제)
        run: |
          docker ps -q --filter "name=woori-node-test" | xargs -r docker stop
          docker ps -aq --filter "name=woori-node-test" | xargs -r docker rm
          docker images -q woori-node-test | xargs -r docker rmi -f

      - name: 테스트용_이미지_빌드
        run: |
          docker build -t woori-node-test .

      - name: 테스트서버_3000번포트_가동
        run: |
          docker run -d --name woori-node-test -p 3000:80 woori-node-test